
version: '2'
services:
  influxdb:
    image: influxdb
    ports:
      - 8086:8086
    volumes:
      - ./influxdb/etc/:/etc/influxdb
      - ./influxdb/var:/var/lib/influxdb
      - /etc/localtime:/etc/localtime:ro
  
  # MQTT Broker in Docker
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - /etc/localtime:/etc/localtime:ro
  
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/etc:/etc/grafana
      - ./grafana/var:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
